In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 76961 entries, 0 to 76960
Data columns (total 17 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   INEZ-Nummer                         76961 non-null  str
 1   Bescheiddatum                       76961 non-null  datetime64[us]
 2   Bescheidart                         76961 non-null  str
 3   Zuwendungsempfänger                 76961 non-null  str
 4   Behörde                             76961 non-null  str
 5   Dienststelle                        72731 non-null  str
 6   AKZ                                 76954 non-null  str
 7   ZuwendungszeitraumVon               76961 non-null  datetime64[us]
 8   ZuwendungszeitraumBis               76961 non-null  datetime64[us]
 9   Zuwendungszweck                     76961 non-null  str
 10  Förderungsart                       76959 non-null  str
 11  Finanzierungsart                    76959 non-null  str
 12  Finanzierungsform                   76950 non-null  str
 13  Summe von Betriebskostenanteil      59421 non-null  float64
 14  Summe von Investitionskostenanteil  59421 non-null  float64
 15  Summe von Rückforderungen           59421 non-null  float64
 16  Summe von Zuwendungssumme           76961 non-null  float64
dtypes: datetime64[us](3), float64(4), str(10)
memory usage: 10.0 MB

In [6]:
empfaenger_summe = df.groupby("Zuwendungsempfänger")["Summe von Zuwendungssumme"].sum()
empfaenger_summe.sort_values(ascending=False).head(10)

Zuwendungsempfänger
Hamburger Hochbahn Aktiengesellschaft                                      8.667094e+09
Universitätsklinikum Hamburg-Eppendorf                                     6.393099e+09
Hamburg Port Authority AöR                                                 6.031203e+09
Hamburgische Staatsoper Gesellschaft mit beschränkter Haftung              3.486135e+09
Historische Museen Hamburg                                                 1.342463e+09
Neue Schauspielhaus-Gesellschaft mit beschränkter Haftung                  1.271388e+09
Thalia Theater Gesellschaft mit beschränkter Haftung                       1.174527e+09
Hamburger Kunsthalle Stiftung öffentlichen Rechts                          9.637956e+08
HGV Hamburger Gesellschaft f. Vermögens- und Beteiligungsmanagement mbH    9.518300e+08
DB InfraGO Aktiengesellschaft                                              8.610095e+08
Name: Summe von Zuwendungssumme, dtype: float64

In [8]:
mask = df.loc[:, "Zuwendungsempfänger"] == "Hamburger Hochbahn Aktiengesellschaft"
df.loc[mask, ["Bescheiddatum", "Bescheidart", "ZuwendungszeitraumVon", "ZuwendungszeitraumBis", "Summe von Zuwendungssumme"]]

,Bescheiddatum,Bescheidart,ZuwendungszeitraumVon,ZuwendungszeitraumBis,Summe von Zuwendungssumme
350,2025-12-17,Änderungsbescheid,2022-06-01,2025-12-31,"585,590.00"
1126,2025-12-03,Änderungsbescheid,2016-12-08,2019-12-31,"1,439,926.70"
1555,2025-11-24,Änderungsbescheid,2016-03-15,2020-12-31,"18,697,758.18"
1627,2025-11-20,Änderungsbescheid,2019-09-26,2031-06-30,"9,750,000.00"
1628,2025-11-20,Zuwendungsbescheid,2025-01-01,2025-12-31,"5,000,000.00"
...,...,...,...,...,...
71966,2016-06-21,Zuwendungsbescheid,2015-11-25,2020-12-31,"15,000,000.00"
72453,2016-05-04,Änderungsbescheid,2015-03-30,2017-12-31,"22,790,000.00"
72994,2016-03-15,Zuwendungsbescheid,2015-10-09,2017-12-31,"2,000,000.00"
75815,2015-08-31,Zuwendungsbescheid,2015-03-30,2017-12-31,"22,881,000.00"
76342,2015-06-04,Zuwendungsbescheid,2015-11-24,2016-12-31,"800,000.00"

In [7]:
pd.options.display.float_format = "{:,.2f}".format
empfaenger_summe.sort_values(ascending=False).head(10)

Zuwendungsempfänger
Hamburger Hochbahn Aktiengesellschaft                                     8,667,094,000.14
Universitätsklinikum Hamburg-Eppendorf                                    6,393,098,562.94
Hamburg Port Authority AöR                                                6,031,202,874.22
Hamburgische Staatsoper Gesellschaft mit beschränkter Haftung             3,486,134,624.72
Historische Museen Hamburg                                                1,342,463,096.99
Neue Schauspielhaus-Gesellschaft mit beschränkter Haftung                 1,271,387,760.87
Thalia Theater Gesellschaft mit beschränkter Haftung                      1,174,526,630.17
Hamburger Kunsthalle Stiftung öffentlichen Rechts                           963,795,578.57
HGV Hamburger Gesellschaft f. Vermögens- und Beteiligungsmanagement mbH     951,830,000.00
DB InfraGO Aktiengesellschaft                                               861,009,528.24
Name: Summe von Zuwendungssumme, dtype: float64

In [3]:
import pandas as pd
df = pd.read_excel("../data/raw/zuwendungen_2025.xlsx")
df.head()

,INEZ-Nummer,Bescheiddatum,Bescheidart,Zuwendungsempfänger,Behörde,Dienststelle,AKZ,ZuwendungszeitraumVon,ZuwendungszeitraumBis,Zuwendungszweck,Förderungsart,Finanzierungsart,Finanzierungsform,Summe von Betriebskostenanteil,Summe von Investitionskostenanteil,Summe von Rückforderungen,Summe von Zuwendungssumme
0,ZUW-2025-03644,2025-12-30,Zuwendungsbescheid,"Haus 3, Stadtteilzentrum in Altona e.V.",Bezirksamt Altona,NaN,ZUW-2025-03644-InstiFö Haus 3,2026-01-01,2026-12-31,"Institutionelle Förderung der Sach-, Betriebs-...",Institutionelle Förderung,Festbetragsfinanzierung,Nicht rückzahlbarer Zuschuss,NaN,NaN,NaN,437540.90
1,ZUW-2025-02032,2025-12-30,Zuwendungsbescheid,PASSAGE gemeinnützige Gesellschaft für Arbeit ...,"Behörde für Wirtschaft, Arbeit und Innovation",IT-Ressourcen,"Z.601.15-1-2,2026",2026-01-01,2026-12-31,Optimierung der Beschäftigungsfähigkeit und Ar...,Projektförderung,Fehlbedarfsfinanzierung,Nicht rückzahlbarer Zuschuss,NaN,NaN,NaN,333358.62
2,ZUW-2025-00827,2025-12-30,Zuwendungsbescheid,HEnW KommunalEnergie GmbH,"Behörde für Umwelt, Klima, Energie und Agrarwi...",NaN,ZUW-2025-00827,2025-10-28,2026-10-31,Datenschutzwürdiger Zweck,Projektförderung,Fehlbedarfsfinanzierung,Nicht rückzahlbarer Zuschuss,NaN,NaN,NaN,245000.00
3,ZUW-2025-03850,2025-12-30,Zuwendungsbescheid,Stiftung Zukunftsrat Hamburg e.V.,"Behörde für Umwelt, Klima, Energie und Agrarwi...",NaN,ZUW-2025-03850,2026-01-01,2026-12-31,Förderung des laufenden Betriebs und der Aktiv...,Projektförderung,Fehlbedarfsfinanzierung,Nicht rückzahlbarer Zuschuss,NaN,NaN,NaN,57000.00
4,ZUW-2025-03985,2025-12-30,Zuwendungsbescheid,Initiative Schwarze Menschen in Deutschland (I...,Behörde für Kultur und Medien,NaN,ZUW-2025-03985,2025-12-19,2026-05-31,Ausstellung und Film - 30 Jahre BHM in Hamburg,Projektförderung,Fehlbedarfsfinanzierung,Nicht rückzahlbarer Zuschuss,NaN,NaN,NaN,24020.00